name: CI Pipeline

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install C++ and CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake

    - name: Install Google Test
      run: |
        sudo apt-get install -y libgtest-dev
        sudo apt-get install -y cmake
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp ./lib/libgtest*.a /usr/lib

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run Tests
      run: ./build/test/test_matrix_multiplication


